### ISSUE TITLE
Deprecate repo?

### ISSUE THREAD

**Issue by dandv** [Sanjo/meteor-es6#2]
Now that [ES6 is getting official support in Meteor](https://forums.meteor.com/t/devshop-sf-july-2015/7743/2?u=dandv) and there are more advanced packages like rocket:module or universe:module.

**Comment by Sanjo** [comment]
How would you suggest that I should deprecate the package? Add a deprecation message to the README?

**Comment by dandv** [comment]
That, then `meteor publish --update` then `meteor admin set-unmigrated sanjo:es6-now`.

**Comment by Sanjo** [comment]
Done

**Comment by trusktr** [comment]
@dandv @Sanjo Keep in mind that, if Meteor [decides](https://forums.meteor.com/t/try-out-a-preview-of-batch-build-plugins-and-other-1-2-features/7374/22?u=joe) [to add](https://github.com/meteor/meteor/commit/f7ee0ba38507d1cca8ff6c1f8112d6e3f9835883#commitcomment-12310720) compiler "pass through", these packages will still be useful.
